version: "2"
linters:
  enable:
    - dupl
    - errcheck
    - errchkjson
    - exhaustruct
    - exhaustive
    - gochecksumtype
    - goconst
    - gocritic
    - godox
    - gosec
    - govet
    - gocheckcompilerdirectives
    - misspell
    - musttag
    - nestif
    - nilerr
    - nosprintfhostport
    - perfsprint
    - predeclared
    - prealloc
    - usestdlibvars
    - unparam
    - unconvert
  settings:
    exhaustruct:
      allow-empty-rx:
        - '.*/validation\.ValidateStructMixin'
        - '.*/bun\.BaseModel'
      allow-empty-returns: true
    exhaustive:
      default-case-required: true
      default-signifies-exhaustive: false
      explicit-exhaustive-switch: false
      explicit-exhaustive-map: false
    errchkjson:
      report-no-exported: true
    gocritic:
      enabled-tags:
        - performance
        - diagnostic
    gochecksumtype:
      default-signifies-exhaustive: true
      include-shared-interfaces: true
    dupl:
      threshold: 150
