// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package daos

import (
	"database/sql"
)

type Artifact struct {
	ID            interface{}
	Content       []byte
	ContentSha256 string
	Type          string
	LastModified  interface{}
	CollectionID  sql.NullString
}

type Collection struct {
	ID             interface{}
	Name           string
	IsFolderScoped int64
	FolderHash     sql.NullString
	LastModified   interface{}
}
