// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package daos

import (
	"database/sql"
)

type Artifact struct {
	ID           interface{}
	Content      []byte
	Type         string
	CreatedAt    interface{}
	LastModified sql.NullInt64
	CollectionID sql.NullString
}

type Collection struct {
	ID             interface{}
	Name           string
	IsFolderScoped int64
	FolderHash     sql.NullString
	CreatedAt      interface{}
	LastModified   sql.NullInt64
}
