name: Test
on:
  push:
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
  pull_request:
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      # ---------------------------------------------------------------
      # Linux-only: install clipboard deps + virtual X server
      # ---------------------------------------------------------------
      - name: Install clipboard deps (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb xclip
      # ---------------------------------------------------------------
      # - macOS / Windows: plain
      # - Linux: under `xvfb-run` so xclip finds a DISPLAY (:99)
      # ---------------------------------------------------------------
      - name: Test
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" go test ./...
          else
            go test ./...
          fi
